# Generated by Django 4.1.13 on 2024-10-29 18:08

from django.db import migrations, models
import mock.models


class Migration(migrations.Migration):

    dependencies = [
        ('mock', '0008_mockapiresponsehandler_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockproject',
            name='project_id',
            field=models.CharField(default=mock.models.generate_short_id, max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='MockAPIResponseHandler',
        ),
    ]
